import type { Metadata } from "next";
import { Space_Grotesk, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

// const inter = Inter({ subsets: ["latin"], variable: "--inter-font" });
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: [ "300", "400", "500", "700"],
  variable: "--spaceGrotesk-font",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--roboto-font",
});

export const metadata: Metadata = {
  title: "Nisa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${spaceGrotesk.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
